### ISSUE TITLE
Add form validation for the submission

### ISSUE THREAD

**Issue by reachjason** [yblockchain/yblockchain.github.io#1]
It is easy to submit a form with nothing. We could add validation to check if anything is not an empty string and/or email address has "@" in it.

**Comment by yblockchain** [comment]
It's already there. Try adding a null value and the form will not be accepted.
Also, the email validation is in place, so yeah.

**Comment by reachjason** [comment]
Is this in Google Forms from or Javascript? Personally having both is important, serves as feedback to the user.

**Comment by reachjason** [comment]
Fixed this.
